<a href="https://colab.research.google.com/github/19pa1a0220/AI-LAB/blob/master/AI-Lab_Experiment-1_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EXPERIMENT-1_NUMPY


##i) Different ways to create NumPy arrays

In [ ]:
#1-d array
import numpy as np
a = np.array([1,4,3])
print (a)

[1 4 3]


In [ ]:
#2-d array
a = np.array([[1, 2], [3, 4]])
print (a)

[[1 2]
 [3 4]]


##ii) Add, remove, modify elements in an array

###1-numpy.arange

In [ ]:
import numpy as np
np.arange( 10, 50, 5 )

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

###2-numpy.reshape

In [ ]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

###3-ndarray.shape

In [ ]:
a.shape

(4, 5)

###4-ndarray.ndim

In [ ]:
a.ndim

2

###5-ndarray.dtype

In [ ]:
a.dtype

dtype('int64')

###6-ndarray.itemsize

In [ ]:
a.size

20

###7-type(ndarray)

In [ ]:
type(a)

numpy.ndarray

###8-numpy.zeros , numpy.ones , numpy.empty, numpy.eye, numpy.full and numpy.random.

In [ ]:
np.zeros( (3,4) ) # creates an arrays of all zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones( (2,3), dtype=np.int16 ) #  creates an array of all ones. dtype can also be specified

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [ ]:
np.empty( (2,3) )  # Creates an empty array. Note that the numbers are the elements at that location

array([[1.58400055e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
np.eye(3) # Creates identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.full((2,2),7) # Creates a matrix with the specified elements

array([[7, 7],
       [7, 7]])

In [ ]:
a = np.random.random((2,3)) # Creates a matrix with some random numbers
a

array([[0.22057716, 0.97499101, 0.32754134],
       [0.73182714, 0.48855619, 0.10659982]])

##iii) Arithmetic operations on NumPy array

###1-Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result

In [ ]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print(a)
print(b)
c = a-b
print(c)
print(b**2)
print(10*np.sin(a))
print(a<35)
a[0] +=10
print(a)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]
[30 30 40 50]


###2-Dot method

In [12]:
import numpy as np
A = np.array( [[1,2],[0,1]] )
B = np.array( [[2,0],[4,4]] )

print(A)
print(B)

print(A * B)  # elementwise product

print(A @ B)  # matrix product

print(A.dot(B)) # another matrix product

print(np.dot(A,B)) # another matrix product

[[1 2]
 [0 1]]
[[2 0]
 [4 4]]
[[2 0]
 [0 4]]
[[10  8]
 [ 4  4]]
[[10  8]
 [ 4  4]]
[[10  8]
 [ 4  4]]


###3-Use of axis

In [13]:
b=np.arange(20).reshape(4,5)
print(b)
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))
print(b.min(axis=1))
print(b.cumsum(axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
190
[30 34 38 42 46]
[10 35 60 85]
[ 0  5 10 15]
[[ 0  1  3  6 10]
 [ 5 11 18 26 35]
 [10 21 33 46 60]
 [15 31 48 66 85]]


###4-Basic mathematical functions

In [ ]:
a=np.arange(5)
print(a)

b=np.random.random(5)
print(b)

print(np.add(a,b))
print(a + b)
print(a - b)
print(np.subtract(a, b))
print(a * b)
print(np.multiply(a, b))
print(a/b)
print(np.divide(a, b))

[0 1 2 3 4]
[0.26516418 0.19755032 0.25953732 0.15803012 0.87670288]
[0.26516418 1.19755032 2.25953732 3.15803012 4.87670288]
[0.26516418 1.19755032 2.25953732 3.15803012 4.87670288]
[-0.26516418  0.80244968  1.74046268  2.84196988  3.12329712]
[-0.26516418  0.80244968  1.74046268  2.84196988  3.12329712]
[0.         0.19755032 0.51907464 0.47409037 3.5068115 ]
[0.         0.19755032 0.51907464 0.47409037 3.5068115 ]
[ 0.          5.06200144  7.7060209  18.98372246  4.56254919]
[ 0.          5.06200144  7.7060209  18.98372246  4.56254919]


##iv) Slicing and iterating of NumPy arrays

###1-Slicing-access list of elements

In [ ]:
#Slicing a 1-D array
a=np.arange(10)**3
print(a)
print(a[2])
print(a[2:4]) 
print(a[2:3])

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27]
[8]


In [ ]:
#Slicing a 2-D array
a=np.arange(12).reshape(4,3)**2
print(a)
print(a[1:3])
print(a[1:3,1:2])
print(a[2,])
print(a[:2],)
print(a[:3,])
print(a[:3,:2])
print(a[:,2])

[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]
[[ 9 16 25]
 [36 49 64]]
[[16]
 [49]]
[36 49 64]
[[ 0  1  4]
 [ 9 16 25]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
[[ 0  1]
 [ 9 16]
 [36 49]]
[  4  25  64 121]


##using negative indentation

In [ ]:
#1-D array
a=np.arange(10)**3
print(a)
print(a[-1])
print(a[-2])
print(a[-5:-2])

[  0   1   8  27  64 125 216 343 512 729]
729
512
[125 216 343]


In [ ]:
#2-D array
a=np.arange(12).reshape(4,3)**2 
print(a)
print(a[-1,])
print(a[-1,-1]) 
print(a[-3:-1,-2:])

[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]
[ 81 100 121]
121
[[16 25]
 [49 64]]


###2-Iterating

In [ ]:
a=np.arange(12).reshape(4,3)**2
print(a)

for i in a:
    print(i)

[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]
[0 1 4]
[ 9 16 25]
[36 49 64]
[ 81 100 121]


In [ ]:
for i in a.flat:
  print(i)

0
1
4
9
16
25
36
49
64
81
100
121


##V) Matrix operations on NumPy arrays

###1-Difference between resize and reshape

In [ ]:
a=np.floor(10*np.random.random((3,4)))
a

array([[3., 0., 7., 1.],
       [2., 0., 4., 5.],
       [9., 6., 9., 1.]])

In [ ]:
a.reshape(2,6)

array([[3., 0., 7., 1., 2., 0.],
       [4., 5., 9., 6., 9., 1.]])

In [ ]:
a

array([[3., 0., 7., 1.],
       [2., 0., 4., 5.],
       [9., 6., 9., 1.]])

In [ ]:
a.resize(2,6)

In [ ]:
a

array([[3., 0., 7., 1., 2., 0.],
       [4., 5., 9., 6., 9., 1.]])

###2-function to flatten an array

In [ ]:
a.ravel()
a

array([[3., 0., 7., 1., 2., 0.],
       [4., 5., 9., 6., 9., 1.]])

###3-To find transpose of matrix

In [ ]:
a.T

array([[3., 4.],
       [0., 5.],
       [7., 9.],
       [1., 6.],
       [2., 9.],
       [0., 1.]])

###4.stacking together different arrays

In [ ]:
# Create 2 matrices

a=np.floor(10*np.random.random((2,2)))
print(a)

b=np.floor(10*np.random.random((2,2)))
print(b)

[[0. 3.]
 [0. 7.]]
[[6. 2.]
 [7. 4.]]


In [ ]:
np.vstack((a,b))

array([[0., 1.],
       [7., 2.],
       [4., 2.],
       [0., 5.]])

In [ ]:
np.hstack((a,b))

array([[0., 1., 4., 2.],
       [7., 2., 0., 5.]])

###5-splitting one array into several smaller ones

In [ ]:
a=np.array([[11,12,13,14,15,16],[17,19,23,24,25,34]])
print(a)

np.hsplit(a,3) 

[[11 12 13 14 15 16]
 [17 19 23 24 25 34]]


[array([[11, 12],
        [17, 19]]), array([[13, 14],
        [23, 24]]), array([[15, 16],
        [25, 34]])]

In [ ]:
np.hsplit(a,(3,4))

[array([[11, 12, 13],
        [17, 19, 23]]), array([[14],
        [24]]), array([[15, 16],
        [25, 34]])]

In [ ]:
np.vsplit(a,2)

[array([[11, 12, 13, 14, 15, 16]]), array([[17, 19, 23, 24, 25, 34]])]

###6-Broadcasting

In [ ]:
a=np.array([[11,22,33],[44,55,66],[12,14,34]])
a

b=np.array([1,2,3])
b

array([1, 2, 3])

In [ ]:
c=a+b
c

array([[12, 24, 36],
       [45, 57, 69],
       [13, 16, 37]])